name: 변경된 모듈 패키지 생성

on:
  workflow_call:
    inputs:
      module-path:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "0단계: 체크아웃"
        uses: actions/checkout@v4

      - name: "1단계: JDK 설정 - corretto-21"
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: "2단계: 코드 빌드"
        env:
          MODULE_PATH: ${{ inputs.module-path }}
        run: |
          echo "코드를 빌드합니다... $MODULE_PATH"
          MODULE="${MODULE_PATH//\//:}"
          ./gradlew :$MODULE:clean --info
          ./gradlew :$MODULE:build --info

      - name: "3단계: 패키지 생성"
        env:
          MODULE_PATH: ${{ inputs.module-path }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :$MODULE_PATH:publish --info
